# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "Current Directory: $(System.DefaultWorkingDirectory)"
      pwd
      ls -al
    displayName: "Debug The () Current Directory (Linux/macOS)"
  - task: QodanaScan@2025
    env: 
      QODANA_TOKEN: $(QODANA_TOKEN_QA)
    inputs:
      args: '--config,qodana.yaml,--ide, QDNET'
      uploadResult: true
      prMode: true
      useNightly: true