name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Add coverlet dependencies
        working-directory: Tests
        run: |
          dotnet add package coverlet.msbuild; dotnet add package coverlet.collector

      - name: Build solution
        working-directory: .
        run: dotnet build

      - name: Run tests with code coverage
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=../.qodana/code-coverage/ /p:CoverletOutputFormat=lcov
        working-directory: Tests

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: ./.qodana/code-coverage
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "--linter,${{ secrets.SPACE_REGISTRY }}/p/sa/containers/qodana-dotnet:2024.3-nightly"
          pr-mode: true
